# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Constraints.xdc

# IP: ip/AA_1_fir/AA_1_fir.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AA_1_fir || ORIG_REF_NAME==AA_1_fir} -quiet] -quiet
