# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/School/SeniorProject/pmod_i2s2_passthrough/pmod_i2s2_passthrough.srcs/sources_1/ip/AA_1_fir/AA_1_fir.xci
# IP: The module: 'AA_1_fir' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/School/SeniorProject/pmod_i2s2_passthrough/pmod_i2s2_passthrough.gen/sources_1/ip/AA_1_fir/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'AA_1_fir'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/School/SeniorProject/pmod_i2s2_passthrough/pmod_i2s2_passthrough.gen/sources_1/ip/AA_1_fir/AA_1_fir_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AA_1_fir'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/School/SeniorProject/pmod_i2s2_passthrough/pmod_i2s2_passthrough.srcs/sources_1/ip/AA_1_fir/AA_1_fir.xci
# IP: The module: 'AA_1_fir' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/School/SeniorProject/pmod_i2s2_passthrough/pmod_i2s2_passthrough.gen/sources_1/ip/AA_1_fir/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'AA_1_fir'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/School/SeniorProject/pmod_i2s2_passthrough/pmod_i2s2_passthrough.gen/sources_1/ip/AA_1_fir/AA_1_fir_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AA_1_fir'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
