# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/School/SeniorProject/pmod_i2s2_passthrough/pmod_i2s2_passthrough.srcs/sources_1/ip/INT_L_L1_fir_compiler/INT_L_L1_fir_compiler.xci
# IP: The module: 'INT_L_L1_fir_compiler' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/School/SeniorProject/pmod_i2s2_passthrough/pmod_i2s2_passthrough.gen/sources_1/ip/INT_L_L1_fir_compiler/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'INT_L_L1_fir_compiler'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/School/SeniorProject/pmod_i2s2_passthrough/pmod_i2s2_passthrough.gen/sources_1/ip/INT_L_L1_fir_compiler/INT_L_L1_fir_compiler_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'INT_L_L1_fir_compiler'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/School/SeniorProject/pmod_i2s2_passthrough/pmod_i2s2_passthrough.srcs/sources_1/ip/INT_L_L1_fir_compiler/INT_L_L1_fir_compiler.xci
# IP: The module: 'INT_L_L1_fir_compiler' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/School/SeniorProject/pmod_i2s2_passthrough/pmod_i2s2_passthrough.gen/sources_1/ip/INT_L_L1_fir_compiler/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'INT_L_L1_fir_compiler'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/School/SeniorProject/pmod_i2s2_passthrough/pmod_i2s2_passthrough.gen/sources_1/ip/INT_L_L1_fir_compiler/INT_L_L1_fir_compiler_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'INT_L_L1_fir_compiler'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
