# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/natha/OneDrive/Documents/Senior Project/FPGA Code/I2s_in_out/pmod_i2s2_passthrough.srcs/sources_1/ip/L_L1_fir_compiler_1/L_L1_fir_compiler_1.xci
# IP: The module: 'L_L1_fir_compiler_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/natha/OneDrive/Documents/Senior Project/FPGA Code/I2s_in_out/pmod_i2s2_passthrough.gen/sources_1/ip/L_L1_fir_compiler_1/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'L_L1_fir_compiler_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/natha/OneDrive/Documents/Senior Project/FPGA Code/I2s_in_out/pmod_i2s2_passthrough.gen/sources_1/ip/L_L1_fir_compiler_1/L_L1_fir_compiler_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'L_L1_fir_compiler_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/natha/OneDrive/Documents/Senior Project/FPGA Code/I2s_in_out/pmod_i2s2_passthrough.srcs/sources_1/ip/L_L1_fir_compiler_1/L_L1_fir_compiler_1.xci
# IP: The module: 'L_L1_fir_compiler_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/natha/OneDrive/Documents/Senior Project/FPGA Code/I2s_in_out/pmod_i2s2_passthrough.gen/sources_1/ip/L_L1_fir_compiler_1/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'L_L1_fir_compiler_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/natha/OneDrive/Documents/Senior Project/FPGA Code/I2s_in_out/pmod_i2s2_passthrough.gen/sources_1/ip/L_L1_fir_compiler_1/L_L1_fir_compiler_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'L_L1_fir_compiler_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
